require 'AllegroWebApi.rb'
require 'AllegroWebApiMappingRegistry.rb'
require 'soap/rpc/driver'

class AllegroWebApiPortType < ::SOAP::RPC::Driver
  DefaultEndpointUrl = "https://webapi.allegro.pl/uploader.php"
  NsAllegroWebApi = "urn:AllegroWebApi"

  Methods = [
    [ XSD::QName.new(NsAllegroWebApi, "doAddDescToItems"),
      "#doadddesctoitems",
      "doAddDescToItems",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "items-id-array", ["ArrayOfItemsID", "urn:AllegroWebApi", "ArrayOfItemsID"]],
        ["in", "it-description", ["::SOAP::SOAPString"]],
        ["retval", "array-items-add-id", ["ArrayOfItemsID", "urn:AllegroWebApi", "ArrayOfItemsID"]],
        ["out", "array-items-desc-to-long", ["ArrayOfItemsID", "urn:AllegroWebApi", "ArrayOfItemsID"]],
        ["out", "array-items-not-found", ["ArrayOfItemsID", "urn:AllegroWebApi", "ArrayOfItemsID"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doAddPackageInfoToPostBuyForm"),
      "#doaddpackageinfotopostbuyform",
      "doAddPackageInfoToPostBuyForm",
      [ ["in", "session-id", ["::SOAP::SOAPString"]],
        ["in", "transaction-id", ["::SOAP::SOAPLong"]],
        ["in", "package-info", ["ArrayOfPackageInfoStruct", "urn:AllegroWebApi", "ArrayOfPackageInfoStruct"]],
        ["retval", "post-buy-form-package-info", ["PostBuyFormPackageInfoStruct", "urn:AllegroWebApi", "PostBuyFormPackageInfoStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doAddToBlackList"),
      "#doaddtoblacklist",
      "doAddToBlackList",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "users-black-list-array", ["ArrayOfUserBlackListStruct", "urn:AllegroWebApi", "ArrayOfUserBlackListStruct"]],
        ["retval", "user-black-list-results-arr", ["ArrayOfUserBlackListAddResultStruct", "urn:AllegroWebApi", "ArrayOfUserBlackListAddResultStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doAddToWatchList"),
      "#doaddtowatchlist",
      "doAddToWatchList",
      [ ["in", "session-id", ["::SOAP::SOAPString"]],
        ["in", "item-ids", ["ArrayOfItemsID", "urn:AllegroWebApi", "ArrayOfItemsID"]],
        ["retval", "watch-list-info", ["WatchListInfoStruct", "urn:AllegroWebApi", "WatchListInfoStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doBidItem"),
      "#dobiditem",
      "doBidItem",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "bid-it-id", ["::SOAP::SOAPLong"]],
        ["in", "bid-user-price", ["::SOAP::SOAPFloat"]],
        ["in", "bid-quantity", ["::SOAP::SOAPLong"]],
        ["in", "bid-buy-now", ["::SOAP::SOAPLong"]],
        ["in", "pharmacy-recipient-data", ["PharmacyRecipientDataStruct", "urn:AllegroWebApi", "PharmacyRecipientDataStruct"]],
        ["retval", "bid-price", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doCancelBidItem"),
      "#docancelbiditem",
      "doCancelBidItem",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "cancel-item-id", ["::SOAP::SOAPLong"]],
        ["in", "cancel-bids-array", ["ArrayOfCancelBidsID", "urn:AllegroWebApi", "ArrayOfCancelBidsID"]],
        ["in", "cancel-bids-reason", ["::SOAP::SOAPString"]],
        ["in", "cancel-add-to-black-list", ["::SOAP::SOAPLong"]],
        ["retval", "cancel-bid-value", ["::SOAP::SOAPInt"]],
        ["out", "cancelled-bids", ["ArrayOfCancelBidsID", "urn:AllegroWebApi", "ArrayOfCancelBidsID"]],
        ["out", "not-cancelled-bids", ["ArrayOfCancelBidsID", "urn:AllegroWebApi", "ArrayOfCancelBidsID"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doCancelRefundForms"),
      "#docancelrefundforms",
      "doCancelRefundForms",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "refund-cancel-data-arr", ["ArrayOfCancelRefundDataStruct", "urn:AllegroWebApi", "ArrayOfCancelRefundDataStruct"]],
        ["retval", "cancel-refund-forms-results-arr", ["ArrayOfCancelRefundFormResultStruct", "urn:AllegroWebApi", "ArrayOfCancelRefundFormResultStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doCancelRefundWarnings"),
      "#docancelrefundwarnings",
      "doCancelRefundWarnings",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "cancel-refund-warnings-data-arr", ["ArrayOfCancelRefundWarningStruct", "urn:AllegroWebApi", "ArrayOfCancelRefundWarningStruct"]],
        ["retval", "cancel-refund-warnings-results-arr", ["ArrayOfCancelRefundWarningResultStruct", "urn:AllegroWebApi", "ArrayOfCancelRefundWarningResultStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doChangeItemFields"),
      "#dochangeitemfields",
      "doChangeItemFields",
      [ ["in", "session-id", ["::SOAP::SOAPString"]],
        ["in", "item-id", ["::SOAP::SOAPLong"]],
        ["in", "fields-to-modify", ["ArrayOfFieldsValue", "urn:AllegroWebApi", "ArrayOfFieldsValue"]],
        ["in", "fields-to-remove", ["ArrayOfFieldsId", "urn:AllegroWebApi", "ArrayOfFieldsId"]],
        ["in", "preview-only", ["::SOAP::SOAPInt"]],
        ["retval", "changed-item", ["ChangedItemStruct", "urn:AllegroWebApi", "ChangedItemStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doChangePriceItem"),
      "#dochangepriceitem",
      "doChangePriceItem",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "item-id", ["::SOAP::SOAPLong"]],
        ["in", "new-starting-price", ["::SOAP::SOAPFloat"]],
        ["in", "new-reserve-price", ["::SOAP::SOAPFloat"]],
        ["in", "new-buy-now-price", ["::SOAP::SOAPFloat"]],
        ["retval", "item-info", ["::SOAP::SOAPString"]],
        ["out", "item-id", ["::SOAP::SOAPLong"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doChangeQuantityItem"),
      "#dochangequantityitem",
      "doChangeQuantityItem",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "item-id", ["::SOAP::SOAPLong"]],
        ["in", "new-item-quantity", ["::SOAP::SOAPInt"]],
        ["retval", "item-id", ["::SOAP::SOAPLong"]],
        ["out", "item-info", ["::SOAP::SOAPString"]],
        ["out", "item-quantity-left", ["::SOAP::SOAPInt"]],
        ["out", "item-quantity-sold", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doCheckExternalKey"),
      "#docheckexternalkey",
      "doCheckExternalKey",
      [ ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["in", "user-id", ["::SOAP::SOAPLong"]],
        ["in", "item-id", ["::SOAP::SOAPLong"]],
        ["in", "hash-key", ["::SOAP::SOAPString"]],
        ["retval", "result", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doCheckItemDescription"),
      "#docheckitemdescription",
      "doCheckItemDescription",
      [ ["in", "session-id", ["::SOAP::SOAPString"]],
        ["in", "description-content", ["::SOAP::SOAPString"]],
        ["retval", "item-description", ["ItemDescriptionStruct", "urn:AllegroWebApi", "ItemDescriptionStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doCheckNewAuction"),
      "#dochecknewauction",
      "doCheckNewAuction",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "fields", ["ArrayOfFieldsValue", "urn:AllegroWebApi", "ArrayOfFieldsValue"]],
        ["retval", "item-price", ["::SOAP::SOAPString"]],
        ["out", "item-price-desc", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doCheckNewAuctionExt"),
      "#dochecknewauctionext",
      "doCheckNewAuctionExt",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "fields", ["ArrayOfFieldsValue", "urn:AllegroWebApi", "ArrayOfFieldsValue"]],
        ["retval", "item-price", ["::SOAP::SOAPString"]],
        ["out", "item-price-desc", ["::SOAP::SOAPString"]],
        ["out", "item-is-allegro-standard", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doCreateItemTemplate"),
      "#docreateitemtemplate",
      "doCreateItemTemplate",
      [ ["in", "session-id", ["::SOAP::SOAPString"]],
        ["in", "item-template-name", ["::SOAP::SOAPString"]],
        ["in", "item-template-fields", ["ArrayOfFieldsValue", "urn:AllegroWebApi", "ArrayOfFieldsValue"]],
        ["retval", "created-item-template", ["CreatedItemTemplateStruct", "urn:AllegroWebApi", "CreatedItemTemplateStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doFeedback"),
      "#dofeedback",
      "doFeedback",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "fe-item-id", ["::SOAP::SOAPLong"]],
        ["in", "fe-use-comment-template", ["::SOAP::SOAPInt"]],
        ["in", "fe-to-user-id", ["::SOAP::SOAPInt"]],
        ["in", "fe-comment", ["::SOAP::SOAPString"]],
        ["in", "fe-comment-type", ["::SOAP::SOAPString"]],
        ["in", "fe-op", ["::SOAP::SOAPInt"]],
        ["in", "fe-rating", ["ArrayOfSellRatingEstimationStruct", "urn:AllegroWebApi", "ArrayOfSellRatingEstimationStruct"]],
        ["retval", "feedback-id", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doFeedbackMany"),
      "#dofeedbackmany",
      "doFeedbackMany",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "feedbacks-list", ["ArrayOfFeedbackManyStruct", "urn:AllegroWebApi", "ArrayOfFeedbackManyStruct"]],
        ["retval", "fe-results", ["ArrayOfFeedbacksResult", "urn:AllegroWebApi", "ArrayOfFeedbacksResult"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doFindProductByCode"),
      "#dofindproductbycode",
      "doFindProductByCode",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "product-code", ["::SOAP::SOAPString"]],
        ["retval", "products-info", ["ArrayOfProductStruct", "urn:AllegroWebApi", "ArrayOfProductStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doFindProductByName"),
      "#dofindproductbyname",
      "doFindProductByName",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "product-name", ["::SOAP::SOAPString"]],
        ["in", "category-id", ["::SOAP::SOAPLong"]],
        ["retval", "products-info", ["ArrayOfProductStruct", "urn:AllegroWebApi", "ArrayOfProductStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doFinishItem"),
      "#dofinishitem",
      "doFinishItem",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "finish-item-id", ["::SOAP::SOAPLong"]],
        ["in", "finish-cancel-all-bids", ["::SOAP::SOAPInt"]],
        ["in", "finish-cancel-reason", ["::SOAP::SOAPString"]],
        ["retval", "finish-value", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doFinishItems"),
      "#dofinishitems",
      "doFinishItems",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "finish-items-list", ["ArrayOfFinishItemsStruct", "urn:AllegroWebApi", "ArrayOfFinishItemsStruct"]],
        ["retval", "finish-items-succeed", ["ArrayOfFinishSuccessStruct", "urn:AllegroWebApi", "ArrayOfFinishSuccessStruct"]],
        ["out", "finish-items-failed", ["ArrayOfFinishFailureStruct", "urn:AllegroWebApi", "ArrayOfFinishFailureStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetAdminUserLicenceDate"),
      "#dogetadminuserlicencedate",
      "doGetAdminUserLicenceDate",
      [ ["in", "admin-session-handle", ["::SOAP::SOAPString"]],
        ["in", "user-lic-login", ["::SOAP::SOAPString"]],
        ["retval", "get-date-value", ["::SOAP::SOAPFloat"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetBidItem2"),
      "#dogetbiditem2",
      "doGetBidItem2",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "item-id", ["::SOAP::SOAPLong"]],
        ["retval", "biditem-list", ["ArrayOfBidList2", "urn:AllegroWebApi", "ArrayOfBidList2"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetBlackListUsers"),
      "#dogetblacklistusers",
      "doGetBlackListUsers",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["retval", "black-list-users", ["ArrayOfBlackListStruct", "urn:AllegroWebApi", "ArrayOfBlackListStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetCategoryPath"),
      "#dogetcategorypath",
      "doGetCategoryPath",
      [ ["in", "session-id", ["::SOAP::SOAPString"]],
        ["in", "category-id", ["::SOAP::SOAPInt"]],
        ["retval", "category-path", ["ArrayOfCategoryData", "urn:AllegroWebApi", "ArrayOfCategoryData"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetCatsData"),
      "#dogetcatsdata",
      "doGetCatsData",
      [ ["in", "country-id", ["::SOAP::SOAPInt"]],
        ["in", "local-version", ["::SOAP::SOAPLong"]],
        ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["retval", "cats-list", ["ArrayOfCats", "urn:AllegroWebApi", "ArrayOfCats"]],
        ["out", "ver-key", ["::SOAP::SOAPLong"]],
        ["out", "ver-str", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetCatsDataCount"),
      "#dogetcatsdatacount",
      "doGetCatsDataCount",
      [ ["in", "country-id", ["::SOAP::SOAPInt"]],
        ["in", "local-version", ["::SOAP::SOAPLong"]],
        ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["retval", "cats-count", ["::SOAP::SOAPInt"]],
        ["out", "ver-key", ["::SOAP::SOAPLong"]],
        ["out", "ver-str", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetCatsDataLimit"),
      "#dogetcatsdatalimit",
      "doGetCatsDataLimit",
      [ ["in", "country-id", ["::SOAP::SOAPInt"]],
        ["in", "local-version", ["::SOAP::SOAPLong"]],
        ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["in", "offset", ["::SOAP::SOAPInt"]],
        ["in", "package-element", ["::SOAP::SOAPInt"]],
        ["retval", "cats-list", ["ArrayOfCats", "urn:AllegroWebApi", "ArrayOfCats"]],
        ["out", "ver-key", ["::SOAP::SOAPLong"]],
        ["out", "ver-str", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetCountries"),
      "#dogetcountries",
      "doGetCountries",
      [ ["in", "country-code", ["::SOAP::SOAPInt"]],
        ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["retval", "country-array", ["ArrayOfCountries", "urn:AllegroWebApi", "ArrayOfCountries"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetDeals"),
      "#dogetdeals",
      "doGetDeals",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "item-id", ["::SOAP::SOAPLong"]],
        ["in", "buyer-id", ["::SOAP::SOAPInt"]],
        ["retval", "deals-list", ["ArrayOfDealsStruct", "urn:AllegroWebApi", "ArrayOfDealsStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetFavouriteCategories"),
      "#dogetfavouritecategories",
      "doGetFavouriteCategories",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["retval", "s-favourite-categories-list", ["ArrayOfFavouritesCategories", "urn:AllegroWebApi", "ArrayOfFavouritesCategories"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetFavouriteSellers"),
      "#dogetfavouritesellers",
      "doGetFavouriteSellers",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["retval", "s-favourite-sellers-list", ["ArrayOfFavouritesSellers", "urn:AllegroWebApi", "ArrayOfFavouritesSellers"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetFeedback"),
      "#dogetfeedback",
      "doGetFeedback",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "feedback-from", ["::SOAP::SOAPInt"]],
        ["in", "feedback-to", ["::SOAP::SOAPInt"]],
        ["in", "feedback-offset", ["::SOAP::SOAPInt"]],
        ["in", "feedback-kind-list", ["::SOAP::SOAPString"]],
        ["retval", "feedback-list", ["ArrayOfFeedbackList", "urn:AllegroWebApi", "ArrayOfFeedbackList"]],
        ["out", "feedback-count", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetFilledPostBuyForms"),
      "#dogetfilledpostbuyforms",
      "doGetFilledPostBuyForms",
      [ ["in", "session-id", ["::SOAP::SOAPString"]],
        ["in", "payment-type", ["::SOAP::SOAPInt"]],
        ["in", "user-role", ["::SOAP::SOAPInt"]],
        ["in", "filling-time-from", ["::SOAP::SOAPLong"]],
        ["in", "filling-time-to", ["::SOAP::SOAPLong"]],
        ["retval", "filled-post-buy-forms", ["FilledPostBuyFormsStruct", "urn:AllegroWebApi", "FilledPostBuyFormsStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetItemFields"),
      "#dogetitemfields",
      "doGetItemFields",
      [ ["in", "session-id", ["::SOAP::SOAPString"]],
        ["in", "item-id", ["::SOAP::SOAPLong"]],
        ["retval", "item-fields", ["ArrayOfFieldsValue", "urn:AllegroWebApi", "ArrayOfFieldsValue"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetItemTemplates"),
      "#dogetitemtemplates",
      "doGetItemTemplates",
      [ ["in", "session-id", ["::SOAP::SOAPString"]],
        ["in", "item-template-ids", ["ArrayOfTemplatesID", "urn:AllegroWebApi", "ArrayOfTemplatesID"]],
        ["retval", "item-templates", ["ItemTemplatesStruct", "urn:AllegroWebApi", "ItemTemplatesStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetItemsImages"),
      "#dogetitemsimages",
      "doGetItemsImages",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "items-array", ["ArrayOfItemGetImage", "urn:AllegroWebApi", "ArrayOfItemGetImage"]],
        ["in", "image-type", ["::SOAP::SOAPInt"]],
        ["retval", "get_items_images_result", ["ArrayOfItemImagesStruct", "urn:AllegroWebApi", "ArrayOfItemImagesStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetItemsInfo"),
      "#dogetitemsinfo",
      "doGetItemsInfo",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "items-id-array", ["ArrayOfItemsID", "urn:AllegroWebApi", "ArrayOfItemsID"]],
        ["in", "get-desc", ["::SOAP::SOAPInt"]],
        ["in", "get-image-url", ["::SOAP::SOAPInt"]],
        ["in", "get-attribs", ["::SOAP::SOAPInt"]],
        ["in", "get-postage-options", ["::SOAP::SOAPInt"]],
        ["in", "get-company-info", ["::SOAP::SOAPInt"]],
        ["in", "get-product-info", ["::SOAP::SOAPInt"]],
        ["retval", "array-item-list-info", ["ArrayOfStructItemInfoList", "urn:AllegroWebApi", "ArrayOfStructItemInfoList"]],
        ["out", "array-items-not-found", ["ArrayOfItemsID", "urn:AllegroWebApi", "ArrayOfItemsID"]],
        ["out", "array-items-admin-killed", ["ArrayOfItemsID", "urn:AllegroWebApi", "ArrayOfItemsID"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetMessageToBuyer"),
      "#dogetmessagetobuyer",
      "doGetMessageToBuyer",
      [ ["in", "session-id", ["::SOAP::SOAPString"]],
        ["in", "item-id", ["::SOAP::SOAPLong"]],
        ["retval", "message-to-buyer", ["MessageToBuyerStruct", "urn:AllegroWebApi", "MessageToBuyerStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetMyAddresses"),
      "#dogetmyaddresses",
      "doGetMyAddresses",
      [ ["in", "session-id", ["::SOAP::SOAPString"]],
        ["retval", "addresses-info", ["AddressesInfoStruct", "urn:AllegroWebApi", "AddressesInfoStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetMyData"),
      "#dogetmydata",
      "doGetMyData",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["retval", "user-data", ["UserDataStruct", "urn:AllegroWebApi", "UserDataStruct"]],
        ["out", "invoice-data", ["InvoiceDataStruct", "urn:AllegroWebApi", "InvoiceDataStruct"]],
        ["out", "company-extra-data", ["CompanyExtraDataStruct", "urn:AllegroWebApi", "CompanyExtraDataStruct"]],
        ["out", "company-second-address", ["CompanySecondAddressStruct", "urn:AllegroWebApi", "CompanySecondAddressStruct"]],
        ["out", "pharmacy-data", ["PharmacyDataStruct", "urn:AllegroWebApi", "PharmacyDataStruct"]],
        ["out", "alcohol-data", ["AlcoholDataStruct", "urn:AllegroWebApi", "AlcoholDataStruct"]],
        ["out", "related-persons", ["RelatedPersonsStruct", "urn:AllegroWebApi", "RelatedPersonsStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetMyIncomingPayments"),
      "#dogetmyincomingpayments",
      "doGetMyIncomingPayments",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "buyer-id", ["::SOAP::SOAPInt"]],
        ["in", "item-id", ["::SOAP::SOAPLong"]],
        ["in", "trans-recv-date-from", ["::SOAP::SOAPLong"]],
        ["in", "trans-recv-date-to", ["::SOAP::SOAPLong"]],
        ["in", "trans-page-limit", ["::SOAP::SOAPInt"]],
        ["in", "trans-offset", ["::SOAP::SOAPInt"]],
        ["retval", "pay-trans-income", ["ArrayOfUserIncomingPaymentStruct", "urn:AllegroWebApi", "ArrayOfUserIncomingPaymentStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetMyIncomingPaymentsRefunds"),
      "#dogetmyincomingpaymentsrefunds",
      "doGetMyIncomingPaymentsRefunds",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "buyer-id", ["::SOAP::SOAPInt"]],
        ["in", "item-id", ["::SOAP::SOAPLong"]],
        ["in", "limit", ["::SOAP::SOAPInt"]],
        ["in", "offset", ["::SOAP::SOAPInt"]],
        ["retval", "pay-trans-income-refunds", ["ArrayOfUserIncomingPaymentRefundsStruct", "urn:AllegroWebApi", "ArrayOfUserIncomingPaymentRefundsStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetMyPayments"),
      "#dogetmypayments",
      "doGetMyPayments",
      [ ["in", "session-id", ["::SOAP::SOAPString"]],
        ["in", "seller-id", ["::SOAP::SOAPInt"]],
        ["in", "item-id", ["::SOAP::SOAPLong"]],
        ["in", "payment-time-from", ["::SOAP::SOAPLong"]],
        ["in", "payment-time-to", ["::SOAP::SOAPLong"]],
        ["in", "page-size", ["::SOAP::SOAPInt"]],
        ["in", "page-number", ["::SOAP::SOAPInt"]],
        ["retval", "pay-trans-payment", ["ArrayOfUserPaymentStruct", "urn:AllegroWebApi", "ArrayOfUserPaymentStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetMyPaymentsInfo"),
      "#dogetmypaymentsinfo",
      "doGetMyPaymentsInfo",
      [ ["in", "session-id", ["::SOAP::SOAPString"]],
        ["retval", "payments-info", ["PaymentsInfoStruct", "urn:AllegroWebApi", "PaymentsInfoStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetMyPaymentsRefunds"),
      "#dogetmypaymentsrefunds",
      "doGetMyPaymentsRefunds",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "seller-id", ["::SOAP::SOAPInt"]],
        ["in", "item-id", ["::SOAP::SOAPLong"]],
        ["in", "limit", ["::SOAP::SOAPInt"]],
        ["in", "offset", ["::SOAP::SOAPInt"]],
        ["retval", "pay-trans-payment-refunds", ["ArrayOfUserPaymentRefundsStruct", "urn:AllegroWebApi", "ArrayOfUserPaymentRefundsStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetMyPayouts"),
      "#dogetmypayouts",
      "doGetMyPayouts",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "trans-create-date-from", ["::SOAP::SOAPLong"]],
        ["in", "trans-create-date-to", ["::SOAP::SOAPLong"]],
        ["in", "trans-page-limit", ["::SOAP::SOAPInt"]],
        ["in", "trans-offset", ["::SOAP::SOAPInt"]],
        ["retval", "pay-trans-payout", ["ArrayOfUserPayoutStruct", "urn:AllegroWebApi", "ArrayOfUserPayoutStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetMySellRating"),
      "#dogetmysellrating",
      "doGetMySellRating",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["retval", "sell-rating-total-count", ["::SOAP::SOAPInt"]],
        ["out", "sell-rating-average", ["ArrayOfSellRatingAverageStruct", "urn:AllegroWebApi", "ArrayOfSellRatingAverageStruct"]],
        ["out", "sell-rating-details", ["ArrayOfSellRatingDetailStruct", "urn:AllegroWebApi", "ArrayOfSellRatingDetailStruct"]],
        ["out", "sell-rating-stats-per-month", ["ArrayOfSellRatingAveragePerMonth", "urn:AllegroWebApi", "ArrayOfSellRatingAveragePerMonth"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetPaymentData"),
      "#dogetpaymentdata",
      "doGetPaymentData",
      [ ["in", "country-id", ["::SOAP::SOAPInt"]],
        ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["retval", "payment-list", ["ArrayOfBilling", "urn:AllegroWebApi", "ArrayOfBilling"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetPaymentMethods"),
      "#dogetpaymentmethods",
      "doGetPaymentMethods",
      [ ["in", "session-id", ["::SOAP::SOAPString"]],
        ["retval", "payment-methods", ["ArrayOfPaymentMethodStruct", "urn:AllegroWebApi", "ArrayOfPaymentMethodStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetPostBuyData"),
      "#dogetpostbuydata",
      "doGetPostBuyData",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "items-array", ["ArrayOfAuctionID", "urn:AllegroWebApi", "ArrayOfAuctionID"]],
        ["retval", "items-post-buy-data", ["ArrayOfItemsPostBuyData", "urn:AllegroWebApi", "ArrayOfItemsPostBuyData"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetPostBuyFormsDataForBuyers"),
      "#dogetpostbuyformsdataforbuyers",
      "doGetPostBuyFormsDataForBuyers",
      [ ["in", "session-id", ["::SOAP::SOAPString"]],
        ["in", "transactions-ids-array", ["ArrayOfTransactionsID", "urn:AllegroWebApi", "ArrayOfTransactionsID"]],
        ["retval", "post-buy-form-data-for-buyers", ["ArrayOfPostBuyFormForBuyersDataStruct", "urn:AllegroWebApi", "ArrayOfPostBuyFormForBuyersDataStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetPostBuyFormsDataForSellers"),
      "#dogetpostbuyformsdataforsellers",
      "doGetPostBuyFormsDataForSellers",
      [ ["in", "session-id", ["::SOAP::SOAPString"]],
        ["in", "transactions-ids-array", ["ArrayOfTransactionsID", "urn:AllegroWebApi", "ArrayOfTransactionsID"]],
        ["retval", "post-buy-form-data", ["ArrayOfPostBuyFormDataStruct", "urn:AllegroWebApi", "ArrayOfPostBuyFormDataStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetProductCatalogueCategories"),
      "#dogetproductcataloguecategories",
      "doGetProductCatalogueCategories",
      [ ["in", "session-id", ["::SOAP::SOAPString"]],
        ["retval", "product-catalogue-categories", ["ArrayOfCatInfoType", "urn:AllegroWebApi", "ArrayOfCatInfoType"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetProductCategories"),
      "#dogetproductcategories",
      "doGetProductCategories",
      [ ["in", "session-id", ["::SOAP::SOAPString"]],
        ["in", "product-id", ["::SOAP::SOAPLong"]],
        ["retval", "product-categories", ["ArrayOfCatInfoType", "urn:AllegroWebApi", "ArrayOfCatInfoType"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetProductItems"),
      "#dogetproductitems",
      "doGetProductItems",
      [ ["in", "session-id", ["::SOAP::SOAPString"]],
        ["in", "product-id", ["::SOAP::SOAPLong"]],
        ["in", "category-id", ["::SOAP::SOAPInt"]],
        ["in", "page-size", ["::SOAP::SOAPInt"]],
        ["in", "page-number", ["::SOAP::SOAPInt"]],
        ["retval", "product-items-count", ["::SOAP::SOAPInt"]],
        ["out", "product-items-ids", ["ArrayOfProductItemsIds", "urn:AllegroWebApi", "ArrayOfProductItemsIds"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetRefundFormsStatuses"),
      "#dogetrefundformsstatuses",
      "doGetRefundFormsStatuses",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "refund-forms-statuses-data-arr", ["ArrayOfRefundFormStatusStruct", "urn:AllegroWebApi", "ArrayOfRefundFormStatusStruct"]],
        ["retval", "refund-forms-statuses-results-arr", ["ArrayOfRefundFormStatusResultStruct", "urn:AllegroWebApi", "ArrayOfRefundFormStatusResultStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetRefundReasons"),
      "#dogetrefundreasons",
      "doGetRefundReasons",
      [ ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["in", "country-code", ["::SOAP::SOAPInt"]],
        ["retval", "refund-reasons-arr", ["ArrayOfRefundReasonStruct", "urn:AllegroWebApi", "ArrayOfRefundReasonStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetRefundTransactions"),
      "#dogetrefundtransactions",
      "doGetRefundTransactions",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "offset", ["::SOAP::SOAPInt"]],
        ["in", "limit", ["::SOAP::SOAPInt"]],
        ["retval", "refund-forms-count", ["::SOAP::SOAPInt"]],
        ["out", "refund-forms-list", ["ArrayOfRefundFormDataStruct", "urn:AllegroWebApi", "ArrayOfRefundFormDataStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetRelatedItems"),
      "#dogetrelateditems",
      "doGetRelatedItems",
      [ ["in", "session-id", ["::SOAP::SOAPString"]],
        ["in", "item-ids", ["ArrayOfItemsID", "urn:AllegroWebApi", "ArrayOfItemsID"]],
        ["retval", "related-items", ["RelatedItemsStruct", "urn:AllegroWebApi", "RelatedItemsStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetSellFormAttribs"),
      "#dogetsellformattribs",
      "doGetSellFormAttribs",
      [ ["in", "country-id", ["::SOAP::SOAPInt"]],
        ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["in", "local-version", ["::SOAP::SOAPLong"]],
        ["in", "cat-id", ["::SOAP::SOAPInt"]],
        ["retval", "sell-form-fields", ["ArrayOfSellForms", "urn:AllegroWebApi", "ArrayOfSellForms"]],
        ["out", "ver-key", ["::SOAP::SOAPLong"]],
        ["out", "ver-str", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetSellFormFields"),
      "#dogetsellformfields",
      "doGetSellFormFields",
      [ ["in", "country-code", ["::SOAP::SOAPInt"]],
        ["in", "local-version", ["::SOAP::SOAPLong"]],
        ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["retval", "sell-form-fields", ["ArrayOfSellForms", "urn:AllegroWebApi", "ArrayOfSellForms"]],
        ["out", "ver-key", ["::SOAP::SOAPLong"]],
        ["out", "ver-str", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetSellFormFieldsExt"),
      "#dogetsellformfieldsext",
      "doGetSellFormFieldsExt",
      [ ["in", "country-code", ["::SOAP::SOAPInt"]],
        ["in", "local-version", ["::SOAP::SOAPLong"]],
        ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["retval", "sell-form-fields", ["ArrayOfSellForms", "urn:AllegroWebApi", "ArrayOfSellForms"]],
        ["out", "ver-key", ["::SOAP::SOAPLong"]],
        ["out", "ver-str", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetSellFormFieldsExtLimit"),
      "#dogetsellformfieldsextlimit",
      "doGetSellFormFieldsExtLimit",
      [ ["in", "country-code", ["::SOAP::SOAPInt"]],
        ["in", "local-version", ["::SOAP::SOAPLong"]],
        ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["in", "offset", ["::SOAP::SOAPInt"]],
        ["in", "package-element", ["::SOAP::SOAPInt"]],
        ["retval", "sell-form-fields", ["ArrayOfSellForms", "urn:AllegroWebApi", "ArrayOfSellForms"]],
        ["out", "ver-key", ["::SOAP::SOAPLong"]],
        ["out", "ver-str", ["::SOAP::SOAPString"]],
        ["out", "form-fields-count", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetSellFormFieldsForCategory"),
      "#dogetsellformfieldsforcategory",
      "doGetSellFormFieldsForCategory",
      [ ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["in", "country-id", ["::SOAP::SOAPInt"]],
        ["in", "category-id", ["::SOAP::SOAPInt"]],
        ["retval", "sell-form-fields-for-category", ["SellFormFieldsForCategoryStruct", "urn:AllegroWebApi", "SellFormFieldsForCategoryStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetSellFormFieldsLimit"),
      "#dogetsellformfieldslimit",
      "doGetSellFormFieldsLimit",
      [ ["in", "country-code", ["::SOAP::SOAPInt"]],
        ["in", "local-version", ["::SOAP::SOAPLong"]],
        ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["in", "offset", ["::SOAP::SOAPInt"]],
        ["in", "package-element", ["::SOAP::SOAPInt"]],
        ["retval", "sell-form-fields", ["ArrayOfSellForms", "urn:AllegroWebApi", "ArrayOfSellForms"]],
        ["out", "ver-key", ["::SOAP::SOAPLong"]],
        ["out", "ver-str", ["::SOAP::SOAPString"]],
        ["out", "form-fields-count", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetSellRatingReasons"),
      "#dogetsellratingreasons",
      "doGetSellRatingReasons",
      [ ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["in", "country-code", ["::SOAP::SOAPInt"]],
        ["retval", "sell-rating-info", ["ArrayOfSellRatingInfoStruct", "urn:AllegroWebApi", "ArrayOfSellRatingInfoStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetServiceInfo"),
      "#dogetserviceinfo",
      "doGetServiceInfo",
      [ ["in", "country-code", ["::SOAP::SOAPInt"]],
        ["in", "an-cat-id", ["::SOAP::SOAPInt"]],
        ["in", "an-it-date", ["::SOAP::SOAPLong"]],
        ["in", "an-it-id", ["::SOAP::SOAPInt"]],
        ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["retval", "service-info-items-list", ["ArrayOfServiceInfoStruct", "urn:AllegroWebApi", "ArrayOfServiceInfoStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetServiceInfoCategories"),
      "#dogetserviceinfocategories",
      "doGetServiceInfoCategories",
      [ ["in", "country-code", ["::SOAP::SOAPInt"]],
        ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["retval", "service-info-cats-list", ["ArrayOfServiceInfoCatStruct", "urn:AllegroWebApi", "ArrayOfServiceInfoCatStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetServiceTemplates"),
      "#dogetservicetemplates",
      "doGetServiceTemplates",
      [ ["in", "country-code", ["::SOAP::SOAPInt"]],
        ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["retval", "templates-array", ["ArrayOfTemplates", "urn:AllegroWebApi", "ArrayOfTemplates"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetSessionHandleForWidget"),
      "#dogetsessionhandleforwidget",
      "doGetSessionHandleForWidget",
      [ ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["in", "country-code", ["::SOAP::SOAPInt"]],
        ["retval", "session-handle", ["::SOAP::SOAPString"]],
        ["out", "server-time", ["::SOAP::SOAPLong"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetShipmentData"),
      "#dogetshipmentdata",
      "doGetShipmentData",
      [ ["in", "country-id", ["::SOAP::SOAPInt"]],
        ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["retval", "shipment-data-list", ["ArrayOfShipmentDataStruct", "urn:AllegroWebApi", "ArrayOfShipmentDataStruct"]],
        ["out", "local-version", ["::SOAP::SOAPLong"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetShipmentDataForRelatedItems"),
      "#dogetshipmentdataforrelateditems",
      "doGetShipmentDataForRelatedItems",
      [ ["in", "session-id", ["::SOAP::SOAPString"]],
        ["in", "item-ids", ["ArrayOfItemsID", "urn:AllegroWebApi", "ArrayOfItemsID"]],
        ["retval", "related-items-shipment-data", ["RelatedItemsShipmentDataStruct", "urn:AllegroWebApi", "RelatedItemsShipmentDataStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetShopCatsData"),
      "#dogetshopcatsdata",
      "doGetShopCatsData",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["retval", "shop-cats-list", ["ArrayOfCats", "urn:AllegroWebApi", "ArrayOfCats"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetSiteJournal"),
      "#dogetsitejournal",
      "doGetSiteJournal",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "starting-point", ["::SOAP::SOAPLong"]],
        ["in", "info-type", ["::SOAP::SOAPInt"]],
        ["retval", "site-journal-array", ["SiteJournalArray", "urn:AllegroWebApi", "SiteJournalArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetSiteJournalDeals"),
      "#dogetsitejournaldeals",
      "doGetSiteJournalDeals",
      [ ["in", "session-id", ["::SOAP::SOAPString"]],
        ["in", "journal-start", ["::SOAP::SOAPLong"]],
        ["retval", "site-journal-deals", ["ArrayOfSiteJournalDealsStruct", "urn:AllegroWebApi", "ArrayOfSiteJournalDealsStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetSiteJournalDealsInfo"),
      "#dogetsitejournaldealsinfo",
      "doGetSiteJournalDealsInfo",
      [ ["in", "session-id", ["::SOAP::SOAPString"]],
        ["in", "journal-start", ["::SOAP::SOAPLong"]],
        ["retval", "site-journal-deals-info", ["SiteJournalDealsInfoStruct", "urn:AllegroWebApi", "SiteJournalDealsInfoStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetSiteJournalInfo"),
      "#dogetsitejournalinfo",
      "doGetSiteJournalInfo",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "starting-point", ["::SOAP::SOAPLong"]],
        ["in", "info-type", ["::SOAP::SOAPInt"]],
        ["retval", "site-journal-info", ["SiteJournalInfo", "urn:AllegroWebApi", "SiteJournalInfo"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetSitesFlagInfo"),
      "#dogetsitesflaginfo",
      "doGetSitesFlagInfo",
      [ ["in", "country-code", ["::SOAP::SOAPInt"]],
        ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["retval", "sites-info-list", ["ArrayOfSitesFlagInfo", "urn:AllegroWebApi", "ArrayOfSitesFlagInfo"]],
        ["out", "ver-key", ["::SOAP::SOAPLong"]],
        ["out", "ver-str", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetSitesInfo"),
      "#dogetsitesinfo",
      "doGetSitesInfo",
      [ ["in", "country-code", ["::SOAP::SOAPInt"]],
        ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["retval", "sites-info-list", ["ArrayOfSitesInfo", "urn:AllegroWebApi", "ArrayOfSitesInfo"]],
        ["out", "ver-key", ["::SOAP::SOAPLong"]],
        ["out", "ver-str", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetSpecialItems"),
      "#dogetspecialitems",
      "doGetSpecialItems",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "special-type", ["::SOAP::SOAPInt"]],
        ["in", "special-group", ["::SOAP::SOAPInt"]],
        ["in", "offset", ["::SOAP::SOAPInt"]],
        ["in", "order-fulfillment-time", ["::SOAP::SOAPInt"]],
        ["retval", "s-special-list", ["ArrayOfSpecialAuction", "urn:AllegroWebApi", "ArrayOfSpecialAuction"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetStatesInfo"),
      "#dogetstatesinfo",
      "doGetStatesInfo",
      [ ["in", "country-code", ["::SOAP::SOAPInt"]],
        ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["retval", "states-info-array", ["ArrayOfStateInfoStruct", "urn:AllegroWebApi", "ArrayOfStateInfoStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetSystemTime"),
      "#dogetsystemtime",
      "doGetSystemTime",
      [ ["in", "country-id", ["::SOAP::SOAPInt"]],
        ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["retval", "server-time", ["::SOAP::SOAPLong"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetTransactionsIDs"),
      "#dogettransactionsids",
      "doGetTransactionsIDs",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "items-id-array", ["ArrayOfItemsID", "urn:AllegroWebApi", "ArrayOfItemsID"]],
        ["in", "user-role", ["::SOAP::SOAPString"]],
        ["in", "shipment-id-array", ["ArrayOfShipmentIds", "urn:AllegroWebApi", "ArrayOfShipmentIds"]],
        ["retval", "transactions-ids-array", ["ArrayOfTransactionsID", "urn:AllegroWebApi", "ArrayOfTransactionsID"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetUserID"),
      "#dogetuserid",
      "doGetUserID",
      [ ["in", "country-id", ["::SOAP::SOAPInt"]],
        ["in", "user-login", ["::SOAP::SOAPString"]],
        ["in", "user-email", ["::SOAP::SOAPString"]],
        ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["retval", "user-id", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetUserItems"),
      "#dogetuseritems",
      "doGetUserItems",
      [ ["in", "user-id", ["::SOAP::SOAPInt"]],
        ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["in", "country-id", ["::SOAP::SOAPInt"]],
        ["in", "offset", ["::SOAP::SOAPInt"]],
        ["in", "limit", ["::SOAP::SOAPInt"]],
        ["retval", "user-item-list", ["ArrayOfUserItemList", "urn:AllegroWebApi", "ArrayOfUserItemList"]],
        ["out", "user-item-count", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetUserLicenceDate"),
      "#dogetuserlicencedate",
      "doGetUserLicenceDate",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["retval", "get-date-value", ["::SOAP::SOAPFloat"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetUserLogin"),
      "#dogetuserlogin",
      "doGetUserLogin",
      [ ["in", "country-id", ["::SOAP::SOAPInt"]],
        ["in", "user-id", ["::SOAP::SOAPInt"]],
        ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["retval", "user-login", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetWaitingFeedbacks"),
      "#dogetwaitingfeedbacks",
      "doGetWaitingFeedbacks",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "offset", ["::SOAP::SOAPInt"]],
        ["in", "package-size", ["::SOAP::SOAPInt"]],
        ["retval", "fe-wait-list", ["ArrayOfWaitFeedbackStruct", "urn:AllegroWebApi", "ArrayOfWaitFeedbackStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doGetWaitingFeedbacksCount"),
      "#dogetwaitingfeedbackscount",
      "doGetWaitingFeedbacksCount",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["retval", "feedback-count", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doInternalIStoreChange"),
      "#dointernalistorechange",
      "doInternalIStoreChange",
      [ ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["in", "user-id", ["::SOAP::SOAPLong"]],
        ["in", "istore-id", ["::SOAP::SOAPLong"]],
        ["in", "action-type", ["::SOAP::SOAPString"]],
        ["in", "action-date", ["::SOAP::SOAPLong"]],
        ["in", "valid-date", ["::SOAP::SOAPLong"]],
        ["retval", "result", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doInternalSendMessage"),
      "#dointernalsendmessage",
      "doInternalSendMessage",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "user-id", ["::SOAP::SOAPInt"]],
        ["in", "mail_template_id", ["::SOAP::SOAPInt"]],
        ["in", "array-of-additional-data", ["ArrayOfAdditionalData", "urn:AllegroWebApi", "ArrayOfAdditionalData"]],
        ["retval", "result", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doLogin"),
      "#dologin",
      "doLogin",
      [ ["in", "user-login", ["::SOAP::SOAPString"]],
        ["in", "user-password", ["::SOAP::SOAPString"]],
        ["in", "country-code", ["::SOAP::SOAPInt"]],
        ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["in", "local-version", ["::SOAP::SOAPLong"]],
        ["retval", "session-handle-part", ["::SOAP::SOAPString"]],
        ["out", "user-id", ["::SOAP::SOAPLong"]],
        ["out", "server-time", ["::SOAP::SOAPLong"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doLoginEnc"),
      "#dologinenc",
      "doLoginEnc",
      [ ["in", "user-login", ["::SOAP::SOAPString"]],
        ["in", "user-hash-password", ["::SOAP::SOAPString"]],
        ["in", "country-code", ["::SOAP::SOAPInt"]],
        ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["in", "local-version", ["::SOAP::SOAPLong"]],
        ["retval", "session-handle-part", ["::SOAP::SOAPString"]],
        ["out", "user-id", ["::SOAP::SOAPLong"]],
        ["out", "server-time", ["::SOAP::SOAPLong"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doMakeDiscount"),
      "#domakediscount",
      "doMakeDiscount",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "deal-id", ["::SOAP::SOAPLong"]],
        ["in", "discount-amount", ["::SOAP::SOAPFloat"]],
        ["in", "discount-percentage", ["::SOAP::SOAPFloat"]],
        ["retval", "deal-amount-discounted", ["::SOAP::SOAPFloat"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doMakeDiscountByCoupon"),
      "#domakediscountbycoupon",
      "doMakeDiscountByCoupon",
      [ ["in", "session-id", ["::SOAP::SOAPString"]],
        ["in", "discount-data", ["DiscountDataStruct", "urn:AllegroWebApi", "DiscountDataStruct"]],
        ["retval", "item-discount-coupon", ["ItemDiscountCouponStruct", "urn:AllegroWebApi", "ItemDiscountCouponStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doMyAccount2"),
      "#domyaccount2",
      "doMyAccount2",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "account-type", ["::SOAP::SOAPString"]],
        ["in", "offset", ["::SOAP::SOAPInt"]],
        ["in", "items-array", ["ArrayOfAuctionID", "urn:AllegroWebApi", "ArrayOfAuctionID"]],
        ["in", "limit", ["::SOAP::SOAPInt"]],
        ["retval", "myaccount-list", ["ArrayOfMyAccountList2", "urn:AllegroWebApi", "ArrayOfMyAccountList2"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doMyAccountItemsCount"),
      "#domyaccountitemscount",
      "doMyAccountItemsCount",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "account-type", ["::SOAP::SOAPString"]],
        ["in", "items-array", ["ArrayOfAuctionID", "urn:AllegroWebApi", "ArrayOfAuctionID"]],
        ["retval", "myaccount-items-count", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doMyBilling"),
      "#domybilling",
      "doMyBilling",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["retval", "my-billing", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doMyBillingItem"),
      "#domybillingitem",
      "doMyBillingItem",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "item-id", ["::SOAP::SOAPLong"]],
        ["in", "option", ["::SOAP::SOAPString"]],
        ["retval", "entry-fees", ["ItemBillingList", "urn:AllegroWebApi", "ItemBillingList"]],
        ["out", "ending-fees", ["ItemBillingList", "urn:AllegroWebApi", "ItemBillingList"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doMyContact"),
      "#domycontact",
      "doMyContact",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "auction-id-list", ["ArrayOfAuctionID", "urn:AllegroWebApi", "ArrayOfAuctionID"]],
        ["in", "offset", ["::SOAP::SOAPInt"]],
        ["in", "desc", ["::SOAP::SOAPInt"]],
        ["retval", "mycontact-list", ["ArrayOfMyContactList", "urn:AllegroWebApi", "ArrayOfMyContactList"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doMyFeedback2"),
      "#domyfeedback2",
      "doMyFeedback2",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "feedback-type", ["::SOAP::SOAPString"]],
        ["in", "offset", ["::SOAP::SOAPInt"]],
        ["in", "desc", ["::SOAP::SOAPInt"]],
        ["in", "items-array", ["ArrayOfAuctionID", "urn:AllegroWebApi", "ArrayOfAuctionID"]],
        ["retval", "myfeedback-list", ["ArrayOfMyFeedbackList2", "urn:AllegroWebApi", "ArrayOfMyFeedbackList2"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doMyFeedback2Limit"),
      "#domyfeedback2limit",
      "doMyFeedback2Limit",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "feedback-type", ["::SOAP::SOAPString"]],
        ["in", "offset", ["::SOAP::SOAPInt"]],
        ["in", "desc", ["::SOAP::SOAPInt"]],
        ["in", "items-array", ["ArrayOfAuctionID", "urn:AllegroWebApi", "ArrayOfAuctionID"]],
        ["in", "package-element", ["::SOAP::SOAPInt"]],
        ["retval", "myfeedback-list", ["ArrayOfMyFeedbackList2", "urn:AllegroWebApi", "ArrayOfMyFeedbackList2"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doNewAuction"),
      "#donewauction",
      "doNewAuction",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "fields", ["ArrayOfFieldsValue", "urn:AllegroWebApi", "ArrayOfFieldsValue"]],
        ["in", "private", ["::SOAP::SOAPInt"]],
        ["in", "local-id", ["::SOAP::SOAPInt"]],
        ["retval", "item-id", ["::SOAP::SOAPLong"]],
        ["out", "item-info", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doNewAuctionExt"),
      "#donewauctionext",
      "doNewAuctionExt",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "fields", ["ArrayOfFieldsValue", "urn:AllegroWebApi", "ArrayOfFieldsValue"]],
        ["in", "item-template-id", ["::SOAP::SOAPInt"]],
        ["in", "local-id", ["::SOAP::SOAPInt"]],
        ["in", "item-template-create", ["ItemTemplateCreateStruct", "urn:AllegroWebApi", "ItemTemplateCreateStruct"]],
        ["retval", "item-id", ["::SOAP::SOAPLong"]],
        ["out", "item-info", ["::SOAP::SOAPString"]],
        ["out", "item-is-allegro-standard", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doQueryAllSysStatus"),
      "#doqueryallsysstatus",
      "doQueryAllSysStatus",
      [ ["in", "country-id", ["::SOAP::SOAPInt"]],
        ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["retval", "sys-country-status", ["ArrayOfSysStatus", "urn:AllegroWebApi", "ArrayOfSysStatus"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doQuerySysStatus"),
      "#doquerysysstatus",
      "doQuerySysStatus",
      [ ["in", "sysvar", ["::SOAP::SOAPInt"]],
        ["in", "country-id", ["::SOAP::SOAPInt"]],
        ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["retval", "info", ["::SOAP::SOAPString"]],
        ["out", "ver-key", ["::SOAP::SOAPLong"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doRemoveFromBlackList"),
      "#doremovefromblacklist",
      "doRemoveFromBlackList",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "users-id-array", ["ArrayOfUsersID", "urn:AllegroWebApi", "ArrayOfUsersID"]],
        ["retval", "black-list-result", ["ArrayOfBlackListResStruct", "urn:AllegroWebApi", "ArrayOfBlackListResStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doRemoveFromWatchList"),
      "#doremovefromwatchlist",
      "doRemoveFromWatchList",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "items-id-array", ["ArrayOfItemsID", "urn:AllegroWebApi", "ArrayOfItemsID"]],
        ["retval", "watch-list-result", ["ArrayOfItemRemoveWatchStruct", "urn:AllegroWebApi", "ArrayOfItemRemoveWatchStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doRemoveItemTemplates"),
      "#doremoveitemtemplates",
      "doRemoveItemTemplates",
      [ ["in", "session-id", ["::SOAP::SOAPString"]],
        ["in", "item-template-ids", ["ArrayOfTemplatesID", "urn:AllegroWebApi", "ArrayOfTemplatesID"]],
        ["retval", "removed-item-templates", ["RemovedItemTemplatesStruct", "urn:AllegroWebApi", "RemovedItemTemplatesStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doRequestCancelBid"),
      "#dorequestcancelbid",
      "doRequestCancelBid",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "request-item-id", ["::SOAP::SOAPLong"]],
        ["in", "request-cancel-reason", ["::SOAP::SOAPString"]],
        ["retval", "request-value", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doRequestPayout"),
      "#dorequestpayout",
      "doRequestPayout",
      [ ["in", "session-id", ["::SOAP::SOAPString"]],
        ["retval", "request-payout", ["RequestPayoutStruct", "urn:AllegroWebApi", "RequestPayoutStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doRequestSurcharge"),
      "#dorequestsurcharge",
      "doRequestSurcharge",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "transaction-id", ["::SOAP::SOAPLong"]],
        ["in", "surcharge-value", ["::SOAP::SOAPFloat"]],
        ["in", "surcharge-message-to-buyer", ["::SOAP::SOAPString"]],
        ["retval", "surcharge-result", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doSearch"),
      "#dosearch",
      "doSearch",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "search-query", ["SearchOptType", "urn:AllegroWebApi", "SearchOptType"]],
        ["retval", "search-count", ["::SOAP::SOAPInt"]],
        ["out", "search-count-featured", ["::SOAP::SOAPInt"]],
        ["out", "search-array", ["ArrayOfSearchResponse", "urn:AllegroWebApi", "ArrayOfSearchResponse"]],
        ["out", "search-excluded-words", ["ArrayOfExcludedWords", "urn:AllegroWebApi", "ArrayOfExcludedWords"]],
        ["out", "search-categories", ["ArrayOfCategoriesStruct", "urn:AllegroWebApi", "ArrayOfCategoriesStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doSellSomeAgain"),
      "#dosellsomeagain",
      "doSellSomeAgain",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "sell-items-array", ["ArrayOfItemsID", "urn:AllegroWebApi", "ArrayOfItemsID"]],
        ["in", "sell-starting-time", ["::SOAP::SOAPLong"]],
        ["in", "sell-auction-duration", ["::SOAP::SOAPInt"]],
        ["in", "sell-options", ["::SOAP::SOAPInt"]],
        ["in", "local-ids", ["ArrayOfLocalIds", "urn:AllegroWebApi", "ArrayOfLocalIds"]],
        ["retval", "items-sell-again", ["ArrayOfStructSellAgain", "urn:AllegroWebApi", "ArrayOfStructSellAgain"]],
        ["out", "items-sell-failed", ["ArrayOfStructSellFailed", "urn:AllegroWebApi", "ArrayOfStructSellFailed"]],
        ["out", "items-sell-not-found", ["ArrayOfItemsID", "urn:AllegroWebApi", "ArrayOfItemsID"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doSellSomeAgainInShop"),
      "#dosellsomeagaininshop",
      "doSellSomeAgainInShop",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "sell-items-array", ["ArrayOfItemsID", "urn:AllegroWebApi", "ArrayOfItemsID"]],
        ["in", "sell-starting-time", ["::SOAP::SOAPLong"]],
        ["in", "sell-shop-duration", ["::SOAP::SOAPInt"]],
        ["in", "sell-shop-options", ["::SOAP::SOAPInt"]],
        ["in", "sell-prolong-options", ["::SOAP::SOAPInt"]],
        ["in", "sell-shop-category", ["::SOAP::SOAPLong"]],
        ["in", "local-ids", ["ArrayOfLocalIds", "urn:AllegroWebApi", "ArrayOfLocalIds"]],
        ["retval", "items-sell-again", ["ArrayOfStructSellAgain", "urn:AllegroWebApi", "ArrayOfStructSellAgain"]],
        ["out", "items-sell-failed", ["ArrayOfStructSellFailed", "urn:AllegroWebApi", "ArrayOfStructSellFailed"]],
        ["out", "items-sell-not-found", ["ArrayOfItemsID", "urn:AllegroWebApi", "ArrayOfItemsID"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doSendEmailToUser"),
      "#dosendemailtouser",
      "doSendEmailToUser",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "mail-to-user-item-id", ["::SOAP::SOAPLong"]],
        ["in", "mail-to-user-receiver-id", ["::SOAP::SOAPLong"]],
        ["in", "mail-to-user-subject-id", ["::SOAP::SOAPInt"]],
        ["in", "mail-to-user-option", ["::SOAP::SOAPInt"]],
        ["in", "mail-to-user-message", ["::SOAP::SOAPString"]],
        ["retval", "mail-to-user-receiver-id", ["::SOAP::SOAPLong"]],
        ["out", "mail-to-user-result", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doSendPostBuyForm"),
      "#dosendpostbuyform",
      "doSendPostBuyForm",
      [ ["in", "session-id", ["::SOAP::SOAPString"]],
        ["in", "new-post-buy-form-seller", ["ArrayOfNewPostBuyFormSellerStruct", "urn:AllegroWebApi", "ArrayOfNewPostBuyFormSellerStruct"]],
        ["in", "new-post-buy-form-common", ["NewPostBuyFormCommonStruct", "urn:AllegroWebApi", "NewPostBuyFormCommonStruct"]],
        ["retval", "post-buy-form", ["PostBuyFormStruct", "urn:AllegroWebApi", "PostBuyFormStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doSendRefundForms"),
      "#dosendrefundforms",
      "doSendRefundForms",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "send-refund-forms-data-arr", ["ArrayOfSendRefundFormStruct", "urn:AllegroWebApi", "ArrayOfSendRefundFormStruct"]],
        ["retval", "send-refund-forms-results-arr", ["ArrayOfSendRefundFormResultStruct", "urn:AllegroWebApi", "ArrayOfSendRefundFormResultStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doSendReminderMessages"),
      "#dosendremindermessages",
      "doSendReminderMessages",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "send-reminder-messages-data-arr", ["ArrayOfSendReminderMessageStruct", "urn:AllegroWebApi", "ArrayOfSendReminderMessageStruct"]],
        ["retval", "send-reminder-messages-results-arr", ["ArrayOfSendReminderMessageResultStruct", "urn:AllegroWebApi", "ArrayOfSendReminderMessageResultStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doSetUserLicenceDate"),
      "#dosetuserlicencedate",
      "doSetUserLicenceDate",
      [ ["in", "admin-session-handle", ["::SOAP::SOAPString"]],
        ["in", "user-lic-login", ["::SOAP::SOAPString"]],
        ["in", "user-lic-country", ["::SOAP::SOAPInt"]],
        ["in", "user-lic-date", ["::SOAP::SOAPFloat"]],
        ["retval", "set-date-value", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doShowCat"),
      "#doshowcat",
      "doShowCat",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "cat-id", ["::SOAP::SOAPInt"]],
        ["in", "cat-item-state", ["::SOAP::SOAPInt"]],
        ["in", "cat-item-option", ["::SOAP::SOAPInt"]],
        ["in", "cat-item-duration-option", ["DurationTimeInfo", "urn:AllegroWebApi", "DurationTimeInfo"]],
        ["in", "cat-attrib-fields", ["ArrayOfFieldsValue", "urn:AllegroWebApi", "ArrayOfFieldsValue"]],
        ["in", "cat-sort-options", ["::SOAP::SOAPInt"]],
        ["in", "cat-items-price", ["PriceCatInfo", "urn:AllegroWebApi", "PriceCatInfo"]],
        ["in", "cat-items-offset", ["::SOAP::SOAPInt"]],
        ["in", "cat-items-limit", ["::SOAP::SOAPInt"]],
        ["in", "cat-order-fulfillment-time", ["::SOAP::SOAPInt"]],
        ["retval", "cat-parent-array", ["ArrayOfCatInfoStruct", "urn:AllegroWebApi", "ArrayOfCatInfoStruct"]],
        ["out", "cat-child-array", ["ArrayOfCatInfoStruct", "urn:AllegroWebApi", "ArrayOfCatInfoStruct"]],
        ["out", "cat-sister-array", ["ArrayOfCatInfoStruct", "urn:AllegroWebApi", "ArrayOfCatInfoStruct"]],
        ["out", "cat-items-count", ["::SOAP::SOAPInt"]],
        ["out", "cat-items-count-featured", ["::SOAP::SOAPInt"]],
        ["out", "cat-items-array", ["ArrayOfSearchResponse", "urn:AllegroWebApi", "ArrayOfSearchResponse"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doShowItemInfo"),
      "#doshowiteminfo",
      "doShowItemInfo",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "item-id", ["::SOAP::SOAPLong"]],
        ["in", "get-desc", ["::SOAP::SOAPInt"]],
        ["in", "get-image-url", ["::SOAP::SOAPInt"]],
        ["in", "get-attribs", ["::SOAP::SOAPInt"]],
        ["in", "get-postage-options", ["::SOAP::SOAPInt"]],
        ["in", "get-company-info", ["::SOAP::SOAPInt"]],
        ["retval", "item-list-info", ["ItemInfo", "urn:AllegroWebApi", "ItemInfo"]],
        ["out", "item-cat-path", ["ArrayOfItemCatList", "urn:AllegroWebApi", "ArrayOfItemCatList"]],
        ["out", "item-img-list", ["ArrayOfItemImageList", "urn:AllegroWebApi", "ArrayOfItemImageList"]],
        ["out", "item-attrib-list", ["ArrayOfAttribStruct", "urn:AllegroWebApi", "ArrayOfAttribStruct"]],
        ["out", "item-postage-options", ["ArrayOfPostageStruct", "urn:AllegroWebApi", "ArrayOfPostageStruct"]],
        ["out", "item-payment-options", ["ItemPaymentOptions", "urn:AllegroWebApi", "ItemPaymentOptions"]],
        ["out", "item-company-info", ["CompanyInfoStruct", "urn:AllegroWebApi", "CompanyInfoStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doShowItemInfoExt"),
      "#doshowiteminfoext",
      "doShowItemInfoExt",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "item-id", ["::SOAP::SOAPLong"]],
        ["in", "get-desc", ["::SOAP::SOAPInt"]],
        ["in", "get-image-url", ["::SOAP::SOAPInt"]],
        ["in", "get-attribs", ["::SOAP::SOAPInt"]],
        ["in", "get-postage-options", ["::SOAP::SOAPInt"]],
        ["in", "get-company-info", ["::SOAP::SOAPInt"]],
        ["in", "get-product-info", ["::SOAP::SOAPInt"]],
        ["retval", "item-list-info-ext", ["ItemInfoExt", "urn:AllegroWebApi", "ItemInfoExt"]],
        ["out", "item-cat-path", ["ArrayOfItemCatList", "urn:AllegroWebApi", "ArrayOfItemCatList"]],
        ["out", "item-img-list", ["ArrayOfItemImageList", "urn:AllegroWebApi", "ArrayOfItemImageList"]],
        ["out", "item-attrib-list", ["ArrayOfAttribStruct", "urn:AllegroWebApi", "ArrayOfAttribStruct"]],
        ["out", "item-postage-options", ["ArrayOfPostageStruct", "urn:AllegroWebApi", "ArrayOfPostageStruct"]],
        ["out", "item-payment-options", ["ItemPaymentOptions", "urn:AllegroWebApi", "ItemPaymentOptions"]],
        ["out", "item-company-info", ["CompanyInfoStruct", "urn:AllegroWebApi", "CompanyInfoStruct"]],
        ["out", "item-product-info", ["ProductStruct", "urn:AllegroWebApi", "ProductStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doShowUser"),
      "#doshowuser",
      "doShowUser",
      [ ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["in", "country-id", ["::SOAP::SOAPInt"]],
        ["in", "user-id", ["::SOAP::SOAPLong"]],
        ["in", "user-login", ["::SOAP::SOAPString"]],
        ["retval", "user-id", ["::SOAP::SOAPLong"]],
        ["out", "user-login", ["::SOAP::SOAPString"]],
        ["out", "user-country", ["::SOAP::SOAPInt"]],
        ["out", "user-create-date", ["::SOAP::SOAPLong"]],
        ["out", "user-login-date", ["::SOAP::SOAPLong"]],
        ["out", "user-rating", ["::SOAP::SOAPInt"]],
        ["out", "user-is-new-user", ["::SOAP::SOAPInt"]],
        ["out", "user-not-activated", ["::SOAP::SOAPInt"]],
        ["out", "user-closed", ["::SOAP::SOAPInt"]],
        ["out", "user-blocked", ["::SOAP::SOAPInt"]],
        ["out", "user-terminated", ["::SOAP::SOAPInt"]],
        ["out", "user-has-page", ["::SOAP::SOAPInt"]],
        ["out", "user-is-sseller", ["::SOAP::SOAPInt"]],
        ["out", "user-is-eco", ["::SOAP::SOAPInt"]],
        ["out", "user-positive-feedback", ["ShowUserFeedbacks", "urn:AllegroWebApi", "ShowUserFeedbacks"]],
        ["out", "user-negative-feedback", ["ShowUserFeedbacks", "urn:AllegroWebApi", "ShowUserFeedbacks"]],
        ["out", "user-neutral-feedback", ["ShowUserFeedbacks", "urn:AllegroWebApi", "ShowUserFeedbacks"]],
        ["out", "user-junior-status", ["::SOAP::SOAPInt"]],
        ["out", "user-has-shop", ["::SOAP::SOAPInt"]],
        ["out", "user-company-icon", ["::SOAP::SOAPInt"]],
        ["out", "user-sell-rating-count", ["::SOAP::SOAPInt"]],
        ["out", "user-sell-rating-average", ["ArrayOfSellRatingAverageStruct", "urn:AllegroWebApi", "ArrayOfSellRatingAverageStruct"]],
        ["out", "user-is-allegro-standard", ["::SOAP::SOAPInt"]],
        ["out", "user-is-b2c-seller", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doShowUserPage"),
      "#doshowuserpage",
      "doShowUserPage",
      [ ["in", "webapi-key", ["::SOAP::SOAPString"]],
        ["in", "country-id", ["::SOAP::SOAPInt"]],
        ["in", "user-id", ["::SOAP::SOAPLong"]],
        ["retval", "user-page-content", ["::SOAP::SOAPString"]],
        ["out", "user-page-pharmacy-permit", ["::SOAP::SOAPString"]],
        ["out", "user-page-alcohol-permit", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doTranslateProductID"),
      "#dotranslateproductid",
      "doTranslateProductID",
      [ ["in", "session-id", ["::SOAP::SOAPString"]],
        ["in", "bdk-product-id", ["::SOAP::SOAPLong"]],
        ["retval", "translated-product", ["TranslatedProductStruct", "urn:AllegroWebApi", "TranslatedProductStruct"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAllegroWebApi, "doVerifyItem"),
      "#doverifyitem",
      "doVerifyItem",
      [ ["in", "session-handle", ["::SOAP::SOAPString"]],
        ["in", "local-id", ["::SOAP::SOAPInt"]],
        ["retval", "item-id", ["::SOAP::SOAPLong"]],
        ["out", "item-listed", ["::SOAP::SOAPInt"]],
        ["out", "item-starting-time", ["::SOAP::SOAPLong"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ]
  ]

  def initialize(endpoint_url = nil)
    endpoint_url ||= DefaultEndpointUrl
    super(endpoint_url, nil)
    self.mapping_registry = AllegroWebApiMappingRegistry::EncodedRegistry
    self.literal_mapping_registry = AllegroWebApiMappingRegistry::LiteralRegistry
    init_methods
  end

private

  def init_methods
    Methods.each do |definitions|
      opt = definitions.last
      if opt[:request_style] == :document
        add_document_operation(*definitions)
      else
        add_rpc_operation(*definitions)
        qname = definitions[0]
        name = definitions[2]
        if qname.name != name and qname.name.capitalize == name.capitalize
          ::SOAP::Mapping.define_singleton_method(self, qname.name) do |*arg|
            __send__(name, *arg)
          end
        end
      end
    end
  end
end

